INSERT INTO fach VALUES ('GGP', 'wfejan')
INSERT INTO zuweisung VALUES ('3CHIT', 'GGP', 'wfejan')
INSERT INTO fach VALUES ('INSY', 'mmartinides')
INSERT INTO zuweisung VALUES ('3CHIT', 'INSY', 'mmartinides')
INSERT INTO fach VALUES ('NW2', 'ckruisz')
INSERT INTO zuweisung VALUES ('3CHIT', 'NW2', 'ckruisz')
INSERT INTO fach VALUES ('MEDT', 'cbrein')
INSERT INTO zuweisung VALUES ('3AHIT', 'MEDT', 'cbrein')
INSERT INTO zuweisung VALUES ('3BHIT', 'MEDT', 'cbrein')
INSERT INTO zuweisung VALUES ('3CHIT', 'MEDT', 'cbrein')
INSERT INTO fach VALUES ('MEDT', 'jradatz')
INSERT INTO zuweisung VALUES ('3AHIT', 'MEDT', 'jradatz')
INSERT INTO zuweisung VALUES ('3BHIT', 'MEDT', 'jradatz')
INSERT INTO zuweisung VALUES ('3CHIT', 'MEDT', 'jradatz')
INSERT INTO fach VALUES ('MEDT', 'etrenner')
INSERT INTO zuweisung VALUES ('3AHIT', 'MEDT', 'etrenner')
INSERT INTO zuweisung VALUES ('3BHIT', 'MEDT', 'etrenner')
INSERT INTO zuweisung VALUES ('3CHIT', 'MEDT', 'etrenner')
INSERT INTO fach VALUES ('MEDT', 'ewildling')
INSERT INTO zuweisung VALUES ('3AHIT', 'MEDT', 'ewildling')
INSERT INTO zuweisung VALUES ('3BHIT', 'MEDT', 'ewildling')
INSERT INTO zuweisung VALUES ('3CHIT', 'MEDT', 'ewildling')
INSERT INTO fach VALUES ('ITP2', 'reftekhar')
INSERT INTO zuweisung VALUES ('3CHIT', 'ITP2', 'reftekhar')
INSERT INTO fach VALUES ('ITP2', 'bfischer')
INSERT INTO zuweisung VALUES ('3CHIT', 'ITP2', 'bfischer')
INSERT INTO fach VALUES ('ITP2', 'szakall')
INSERT INTO zuweisung VALUES ('3CHIT', 'ITP2', 'szakall')
INSERT INTO fach VALUES ('E1', 'sgradnitzer-pekovits')
INSERT INTO zuweisung VALUES ('3CHIT', 'E1', 'sgradnitzer-pekovits')
INSERT INTO fach VALUES ('E1', 'burbarz')
INSERT INTO zuweisung VALUES ('3CHIT', 'E1', 'burbarz')
INSERT INTO fach VALUES ('AM', 'ckruisz')
INSERT INTO zuweisung VALUES ('3CHIT', 'AM', 'ckruisz')
INSERT INTO fach VALUES ('NWT1', 'bfischer')
INSERT INTO zuweisung VALUES ('3CHIT', 'NWT1', 'bfischer')
INSERT INTO fach VALUES ('SYT', 'jradatz')
INSERT INTO zuweisung VALUES ('3CHIT', 'SYT', 'jradatz')
INSERT INTO fach VALUES ('ITP2', 'wrafeiner-magor')
INSERT INTO zuweisung VALUES ('3CHIT', 'ITP2', 'wrafeiner-magor')
INSERT INTO fach VALUES ('RK', 'cclaucig')
INSERT INTO zuweisung VALUES ('3CHIT', 'RK', 'cclaucig')
INSERT INTO fach VALUES ('BESP', 'wfejan')
INSERT INTO zuweisung VALUES ('3CHIT', 'BESP', 'wfejan')
INSERT INTO fach VALUES ('RISL', 'stuerkmen')
INSERT INTO zuweisung VALUES ('3AHEL', 'RISL', 'stuerkmen')
INSERT INTO zuweisung VALUES ('2CHIT', 'RISL', 'stuerkmen')
INSERT INTO zuweisung VALUES ('3BHIT', 'RISL', 'stuerkmen')
INSERT INTO zuweisung VALUES ('3CHIT', 'RISL', 'stuerkmen')
INSERT INTO zuweisung VALUES ('4AHKT', 'RISL', 'stuerkmen')
INSERT INTO fach VALUES ('GGP', 'hkraus')
INSERT INTO zuweisung VALUES ('3CHIT', 'GGP', 'hkraus')
INSERT INTO zuweisung VALUES ('3AHIT', 'RISL', 'stuerkmen')
INSERT INTO zuweisung VALUES ('2BHMBZ', 'RISL', 'stuerkmen')
INSERT INTO fach VALUES ('D', 'hnordin')
INSERT INTO zuweisung VALUES ('3CHIT', 'D', 'hnordin')
INSERT INTO fach VALUES ('AM', 'mguenthoer')
INSERT INTO zuweisung VALUES ('3CHIT', 'AM', 'mguenthoer')
INSERT INTO fach VALUES ('NWT1', 'pbacsics')
INSERT INTO zuweisung VALUES ('3CHIT', 'NWT1', 'pbacsics')
INSERT INTO fach VALUES ('NWT1', 'aumar')
INSERT INTO zuweisung VALUES ('3CHIT', 'NWT1', 'aumar')
INSERT INTO fach VALUES ('SEW', 'mborko')
INSERT INTO zuweisung VALUES ('3CHIT', 'SEW', 'mborko')
INSERT INTO fach VALUES ('SEW', 'lvittori')
INSERT INTO zuweisung VALUES ('3CHIT', 'SEW', 'lvittori')
INSERT INTO zuweisung VALUES ('3AHIT', 'SYT', 'jradatz')
INSERT INTO zuweisung VALUES ('3BHIT', 'SYT', 'jradatz')
INSERT INTO fach VALUES ('SYT', 'mpaulitsch')
INSERT INTO zuweisung VALUES ('3AHIT', 'SYT', 'mpaulitsch')
INSERT INTO zuweisung VALUES ('3BHIT', 'SYT', 'mpaulitsch')
INSERT INTO zuweisung VALUES ('3CHIT', 'SYT', 'mpaulitsch')
INSERT INTO fach VALUES ('SYT', 'aumar')
INSERT INTO zuweisung VALUES ('3AHIT', 'SYT', 'aumar')
INSERT INTO zuweisung VALUES ('3BHIT', 'SYT', 'aumar')
INSERT INTO zuweisung VALUES ('3CHIT', 'SYT', 'aumar')
INSERT INTO fach VALUES ('SYT', 'pbacsics')
INSERT INTO zuweisung VALUES ('3AHIT', 'SYT', 'pbacsics')
INSERT INTO zuweisung VALUES ('3BHIT', 'SYT', 'pbacsics')
INSERT INTO zuweisung VALUES ('3CHIT', 'SYT', 'pbacsics')
INSERT INTO fach VALUES ('SYT', 'jweiser')
INSERT INTO zuweisung VALUES ('3AHIT', 'SYT', 'jweiser')
INSERT INTO zuweisung VALUES ('3BHIT', 'SYT', 'jweiser')
INSERT INTO zuweisung VALUES ('3CHIT', 'SYT', 'jweiser')
INSERT INTO fach VALUES ('SEW', 'khoeher')
INSERT INTO zuweisung VALUES ('3BHIT', 'SEW', 'khoeher')
INSERT INTO zuweisung VALUES ('3BHIT', 'GGP', 'hkraus')
INSERT INTO fach VALUES ('AM', 'aposekany')
INSERT INTO zuweisung VALUES ('3BHIT', 'AM', 'aposekany')
INSERT INTO fach VALUES ('NW2', 'mioja')
INSERT INTO zuweisung VALUES ('3BHIT', 'NW2', 'mioja')
INSERT INTO fach VALUES ('D', 'burbarz')
INSERT INTO zuweisung VALUES ('3BHIT', 'D', 'burbarz')
INSERT INTO zuweisung VALUES ('3BHIT', 'ITP2', 'szakall')
INSERT INTO zuweisung VALUES ('3BHIT', 'NWT1', 'aumar')
INSERT INTO fach VALUES ('NWT1', 'mfischer')
INSERT INTO zuweisung VALUES ('3BHIT', 'NWT1', 'mfischer')
INSERT INTO zuweisung VALUES ('3BHIT', 'E1', 'sgradnitzer-pekovits')
INSERT INTO zuweisung VALUES ('3BHIT', 'ITP2', 'wrafeiner-magor')
INSERT INTO fach VALUES ('ITP2', 'pbacsics')
INSERT INTO zuweisung VALUES ('3BHIT', 'ITP2', 'pbacsics')
INSERT INTO fach VALUES ('ITP2', 'kkollitsch')
INSERT INTO zuweisung VALUES ('3BHIT', 'ITP2', 'kkollitsch')
INSERT INTO fach VALUES ('E1', 'denzenebner')
INSERT INTO zuweisung VALUES ('3BHIT', 'E1', 'denzenebner')
INSERT INTO zuweisung VALUES ('3BHIT', 'BESP', 'wfejan')
INSERT INTO zuweisung VALUES ('2AHET', 'RISL', 'stuerkmen')
INSERT INTO fach VALUES ('RK', 'cweber')
INSERT INTO zuweisung VALUES ('3BHIT', 'RK', 'cweber')
INSERT INTO fach VALUES ('RE', 'ohackenberg')
INSERT INTO zuweisung VALUES ('4AHBG', 'RE', 'ohackenberg')
INSERT INTO zuweisung VALUES ('3BHIT', 'RE', 'ohackenberg')
INSERT INTO zuweisung VALUES ('3BHIT', 'AM', 'ckruisz')
INSERT INTO zuweisung VALUES ('3BHIT', 'INSY', 'mmartinides')
INSERT INTO fach VALUES ('SEW', 'wrafeiner-magor')
INSERT INTO zuweisung VALUES ('3BHIT', 'SEW', 'wrafeiner-magor')
INSERT INTO fach VALUES ('BSPM', '???')
INSERT INTO zuweisung VALUES ('2BHEL', 'BSPM', '???')
INSERT INTO zuweisung VALUES ('4AHEL', 'BSPM', '???')
INSERT INTO zuweisung VALUES ('1CHBGT', 'BSPM', '???')
INSERT INTO zuweisung VALUES ('4BHBGT', 'BSPM', '???')
INSERT INTO zuweisung VALUES ('3BHIT', 'BSPM', '???')
